
CREATE TABLE IF NOT EXISTS payment_transactions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	service_code VARCHAR(32) NOT NULL,
	amount BIGINT NOT NULL,
	status ENUM('PAYMENT') NOT NULL DEFAULT 'PAYMENT',
	invoice_number VARCHAR(64) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (service_code) REFERENCES services(service_code)
);

CREATE TABLE IF NOT EXISTS balance (
	user_id INT PRIMARY KEY,
	balance BIGINT NOT NULL DEFAULT 0,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS topup_transactions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	amount BIGINT NOT NULL,
	status ENUM('TOPUP') NOT NULL DEFAULT 'TOPUP',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);
